### ISSUE TITLE
hi dude

### ISSUE THREAD

**Issue by idkm23** [hnguyenworkstation/iRobot-Stock-Prediction#1]

**Comment by hnguyenworkstation** [comment]
@idkm23 Hi dude! How are u doing ;)

**Comment by idkm23** [comment]
⠀⠀⠀⠀⢀⠀⢀⣨⣥⣤⣄⣠⠀⠀⣀⣀
⠀⠀⠀⡠⠀⠈⠁⣤⠶⠖⠛⠉⠛⢾⡵⠶⠿⠶⠄⡀
⠀⠀⠠⠀⠀⠀⠋⠄⠀⠀⣾⣛⡆⠀⡆⠀⢸⣛⠆
⠠⠀⠀⠀⠀⠀⢀⡙⠷⢦⣌⡉⣠⠴⠻⣦⠶⢤⡄⠂
⠀⠀⠀⢠⢤⣤⢤⣉⡉⠙⠋⠉⠁⠀⠀⠘⠏⠉⢁⡀
⠀⠀⠀⠀⠸⣯⣿⣿⣽⣽⣶⣶⣶⣶⣖⣶⣖⣾⢽⠇
⠀⠀⠀⠀⠀⠀⠈⠉⠚⠛⠛⠯⠥⠤⠥⠿⠚⠛⠅
⢄
⣿⣯⣶⣄⣂⠤⢤⣄⣀⣀⣀⡠⣤⡄
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣤

**Comment by hnguyenworkstation** [comment]
:pepe:
